- static/css/advisorStudentSchedule.css
- static/js/side-bar.js
- templates/advisorStudentScheduleReview.html
- templates/advisorViewingStudent.html
- templates/studentLanding.html
spent time fixing the UI on my original page that got messed up at the end of last sprint. main features should look correct now.
> Fixed A LOT of the messed-upCSS/html things on my orignial page.

- templates/advisorStudentScheduleReview.html
I think these got deleted when I fixed the merge conflict of Alec's and my branches. These should be more updates to the side bar
> Made the edits to the sidebar display

- server.py
- static/css/advisor-home.css
- static/css/advisorStudentSchedule.css
- static/css/drag-drop.css
- static/css/login.css
- static/css/project.css
- static/css/studentPage.css
- static/js/advisor-home.js
- static/js/drag-drop.js
- templates/advisorLandingPage.html
- templates/advisorStudentScheduleReview.html
- templates/advisorViewingStudent.html
- templates/studentLanding.html
making the pages more unified. Not all the pages scale very nicely but the design is much more unified
> Unify pages

- database.py
- server.py
- static/js/drag-drop.js
- static/js/prereqs.js
- static/js/searchcourses.js
- static/js/status-sheet.js
- templates/advisorStudentScheduleReview.html
course and semester HTML elements are able to track item data using attributes following the name  `data-* `. for example `data-semester" `,`"data-year"` which can be accessed in JavaScript as a dictionary, with `element.dataset.*`. This feature is heavily used to track the placement of courses within the schedule.
> courses with missing Prereqs now highlight yellow

- templates/studentLanding.html
I just forgot to make a change on a certain page...so here it is
> tiny edit that I forgot to make to update a page

- static/js/searchcourses.js
I'm sorry for all of these tiny pull requests! I keep forgetting how many places the same type of thing is!
> one more baby fix

- database.py
- security.py
- server.py
- templates/studentLanding.html
- user.py
This update enforces access protection to all site pages. This includes ensuring the user is authenticated, advisors can only access advisor pages, students can only access student pages, students can only access their own page, and advisors can only access their advisees.
Incorporated the advisor and student access protection within decorators so that future expansions of the app are very easy to add the protection to:
```py
import security
@app.route('/example')
@flask_login.login_required
@security.restrict_to_advisors
def example_advisor_endpoint():
pass
@app.route('/example')
@flask_login.login_required
@security.restrict_to_students
def example_student_endpoint():
pass
```
Additionally, accessing the site login page while being logged in redirects you to the appropriate advisor or …
> Security and validation

- database.py
- server.py
- static/css/advisorStudentSchedule.css
- static/css/drag-drop.css
- static/js/createStudentSchedule.js
- static/js/filtercourses.js
- static/js/searchcourses.js
- templates/advisorStudentScheduleReview.html
I'm making this commit so I can fix some merge conflicts and then pull main fresh to use new features
> not quite done but making good progress!

- static/js/createStudentSchedule.js
- static/js/drag-drop.js
I am pretty sure this is fixed...? I thought that last time though so after merging it should be tested again by someone else to make sure that the bug is actually fixed.
> I am pretty sure that this fixes the problem that Zack found.

- database.py
Added credits to courselist JSON file
> Database code

- server.py
- static/js/advisor-home.js
- templates/advisorLandingPage.html
- templates/advisorStudentScheduleReview.html
- templates/advisorViewingStudent.html
- templates/studentLanding.html
- webscraping/adviseescraper.py
- webscraping/backoff.py
Provides linked navigation between pages that respects state.
> Proper navigation

- database.py
- server.py
- static/js/StudentScheduleLoad.js
- static/js/approveSchedule.js
- static/js/drag-drop.js
- static/js/prereqs.js
- templates/advisorStudentScheduleReview.html
- webscraping/components/schedule.py
Sets the student's status correctly from the student edit page and changes the approve btn to show the correct prompt - also redirects them back to their landing page
> Approve btn/setting status

- database.py
- server.py
- static/js/StudentScheduleLoad.js
- static/js/status-sheet.js
New statussheet and database code for the database
> Status sheet for new Database

- server.py
- static/js/StudentScheduleLoad.js
- static/js/status-sheet.js
server dynamically pulls from db to load user status sheet
> Status sheet

- database.py
- webscraping/adviseescraper.py
Fixes a bug that prevents new advisor login from completing.
> Fixed breaking bugs in advisor cache page.

- database.py
- server.py
- static/js/StudentScheduleLoad.js
- static/js/status-sheet.js
- templates/studentLanding.html
Combines requirements from all majors and minors associated with a student into 1 status sheet
> Support for Double Majors and Minors

- static/js/StudentScheduleLoad.js
> Search on keyup instead of enter

- database.py
- server.py
- static/js/approveSchedule.js
- static/js/prereqs.js
- static/js/status-sheet.js
Corequisites receive warnings now
> Prerequisite checking

- server.py
Added test Dummies, advisor doesnt fully work yet
> Added Test Dummies

- server.py
> Fixed bug that made empty schedules crash

- static/js/StudentScheduleLoad.js
- static/js/advisorApproveSchedule.js
- static/js/prereqs.js
- static/js/status-sheet.js
- static/js/studentApproveSchedule.js
- templates/advisorStudentScheduleReview.html
Some prereqs were not properly tracked, due to a comparison of two strings of different cases
> Fixed a bug with the prerequisite tracking

- static/js/AdviseeScheduleLoad.js
Spinners weren't removed advisor side
> bug fix with the spinners

- server.py
- static/css/drag-drop.css
- static/css/login.css
- static/js/side-bar.js
- templates/advisorViewingStudent.html
- templates/loginPage.html
- templates/studentLanding.html
made a few small UI changes that were tasks in jira - login warning, resize course displayed, open sidebar by default
> made a few small UI changes that were tasks in jira

- static/js/createStudentSchedule.js
- static/js/displayingIntersessionSemesters.js
drag drop now works but the scrapper still needs to be altered
> fixed the drag drop

- static/js/createStudentSchedule.js
- static/js/drag-drop.js
- static/js/filtercourses.js
- static/js/prereqs.js
- templates/advisorStudentScheduleReview.html
Reverts redParrot17/Senior-Project-CAZM#107
> Revert "Warning Tooltips, warning icons"

- static/js/createStudentSchedule.js
- static/js/drag-drop.js
- static/js/filtercourses.js
- static/js/prereqs.js
- templates/advisorStudentScheduleReview.html
> Tooltip Warnings
